version: 0.2      
phases:
  pre_build:
    commands:
      # Log in to Dockerhub
      - echo $DOCKER_CONFIG > ~/.docker/config.json

  build:
    commands:
      - cd components/aws/sagemaker
      - ./codebuild/scripts/deploy.sh -d "${DRY_RUN}"

      - docker build . -f ./sagemaker/integration_tests/Dockerfile -t amazon/integration-test-image --quiet

      # Run the container and copy the results to /tmp
      # Passes all host environment variables through to the container
      - docker run --name integration-test-container $(env | cut -f1 -d= | sed 's/^/-e /') amazon/integration-test-image
      - docker cp integration-test-container:/app/integration_tests/log /tmp/results.xml
      - docker rm -f integration-test-container